language: python

python:
  - "3.6"

cache:
  pip: true

install:
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y
  - pip install pytest pytezos

stages:
  - test
  - name: deploy
    if: (branch = master) AND (tag IS present)

jobs:
  include:
    - stage: test
      script: pytest . -v
    - stage: deploy
      script: pytezos deploy src/atomex.tz --github-repo-slug="$TRAVIS_REPO_SLUG" --github-oauth-token="$GH_TOKEN"